% formation control variable
zji = zeros(dim_xy,1);
z_s_ji = zeros(dim_xy,1);
bar_error_ji = zeros(n_agent,n_agent);

d = 0.15; %[m]

V_SAT = 0.22; %[m/s]
W_SAT = 2.84; %[rad/s]
FOV = 5*D2R; %[rad]
SEARCH_W = 1; %[rad/s]
SUBMODE_TRESHOLD = 1e-3;

buf_Leader = struct( ...
    'mode', zeros(1, t.length), ...
    'lost_leader', zeros(1, t.length), ...
    'lf_losvec', zeros(dim_xy, t.length), ...
    'lf_losang', zeros(dim_th, t.length), ...
    'localization_flag', zeros(1, t.length), ...
    'pos', zeros(dim_xy, t.length), ...
    'pos_dot', zeros(dim_xy, t.length), ...
    'att', zeros(dim_th, t.length), ...
    'att_dot', zeros(dim_th, t.length), ...
    'formation_global', zeros(dim_xy, t.length), ...
    'formation_local', zeros(dim_xy, t.length), ...
    'feedback_linearzed', zeros(dim_xy, t.length), ...
    'localization_input', zeros(dim_xy, t.length));

buf_F1 = struct( ...
    'mode', zeros(1, t.length), ...
    'lost_leader', zeros(1, t.length), ...
    'lf_losvec', zeros(dim_xy, t.length), ...
    'lf_losang', zeros(dim_th, t.length), ...
    'localization_flag', zeros(1, t.length), ...
    'pos', zeros(dim_xy, t.length), ...
    'pos_dot', zeros(dim_xy, t.length), ...
    'att', zeros(dim_th, t.length), ...
    'att_dot', zeros(dim_th, t.length), ...
    'formation_global', zeros(dim_xy, t.length), ...
    'formation_local', zeros(dim_xy, t.length), ...
    'feedback_linearzed', zeros(dim_xy, t.length), ...
    'localization_input', zeros(dim_xy, t.length));

buf_F2 = struct( ...
    'mode', zeros(1, t.length), ...
    'lost_leader', zeros(1, t.length), ...
    'lf_losvec', zeros(dim_xy, t.length), ...
    'lf_losang', zeros(dim_th, t.length), ...
    'localization_flag', zeros(1, t.length), ...
    'pos', zeros(dim_xy, t.length), ...
    'pos_dot', zeros(dim_xy, t.length), ...
    'att', zeros(dim_th, t.length), ...
    'att_dot', zeros(dim_th, t.length), ...
    'formation_global', zeros(dim_xy, t.length), ...
    'formation_local', zeros(dim_xy, t.length), ...
    'feedback_linearzed', zeros(dim_xy, t.length), ...
    'localization_input', zeros(dim_xy, t.length));

buf_L = struct('D', zeros(1,t.length), ...
    'zeta1', zeros(1,t.length), ...
    'zeta2', zeros(dim_xy,t.length), ...
    'zeta1_dot', zeros(1,t.length), ...
    'zeta2_dot', zeros(dim_xy,t.length), ...
    'alpha', 1, ...
    'gamma', 1, ...
    'z_fil', zeros(1,t.length), ...
    'phi_fil', zeros(dim_xy,t.length), ...
    'z_hat', zeros(1,t.length), ...
    'x_hat_dot', zeros(dim_xy,t.length), ...
    'x_hat', zeros(dim_xy,t.length));

BUF = [buf_Leader, buf_F1, buf_F2];