% mode
% 1: formation
% 2: localization
% 3: search leader


% Declare Agent
Leader = struct('node', 'Leader', ...
    'mode', 1, ...
    'submode', 1,...
    'lost_leader', false, ...
    'lf_losvec', zeros(dim_xy,1), ...
    'lf_losang', zeros(dim_th,1), ...
    'localization_flag', false, ...
    'pos', zeros(dim_xy,1), ...
    'pos_dot', zeros(dim_xy,1), ...
    'att', zeros(dim_th,1), ...
    'att_dot', zeros(dim_th,1), ...
    'input_source', zeros(dim_xy, n_agent), ...
    'formation_global', zeros(dim_xy,1), ...
    'formation_local', zeros(dim_xy,1), ...
    'feedback_linearized', zeros(dim_xy,1), ...
    'localization_input', zeros(dim_xy, 1));

F1 = struct('node', 'Follower 1', ...
    'mode', 3, ...
    'submode', 1,...
    'lost_leader', true, ...
    'lf_losvec', zeros(dim_xy,1), ...
    'lf_losang', zeros(dim_th,1), ...
    'localization_flag', false, ...
    'pos', zeros(dim_xy,1), ...
    'pos_dot', zeros(dim_xy,1), ...
    'att', zeros(dim_th,1), ...
    'att_dot', zeros(dim_th,1), ...
    'input_source', zeros(dim_xy, n_agent), ...
    'formation_global', zeros(dim_xy,1), ...
    'formation_local', zeros(dim_xy,1), ...
    'feedback_linearized', zeros(dim_xy,1), ...
    'localization_input', zeros(dim_xy, 1));

F2 = struct('node', 'Follower 2', ...
    'mode', 2, ...
    'submode', 2,...
    'lost_leader', true, ...
    'lf_losvec', zeros(dim_xy,1), ...
    'lf_losang', zeros(dim_th,1), ...
    'localization_flag', true, ...
    'pos', zeros(dim_xy,1), ...
    'pos_dot', zeros(dim_xy,1), ...
    'att', zeros(dim_th,1), ...
    'att_dot', zeros(dim_th,1), ...
    'input_source', zeros(dim_xy, n_agent), ...
    'formation_global', zeros(dim_xy,1), ...
    'formation_local', zeros(dim_xy,1), ...
    'feedback_linearized', zeros(dim_xy,1), ...
    'localization_input', zeros(dim_xy, 1));

L = struct('D', 0, ...
    'zeta1', 0, ...
    'zeta2', zeros(dim_xy,1), ...
    'zeta1_dot', 0, ...
    'zeta2_dot', zeros(dim_xy,1), ...
    'alpha', 1, ...
    'gamma', 1, ...
    'z_fil', 0, ...
    'phi_fil', zeros(dim_xy,1), ...
    'z_hat', 0, ...
    'x_hat', zeros(dim_xy,1), ...
    'x_hat_dot', zeros(dim_xy,1), ...
    'pe_amp', 0.22/sqrt(2), ...
    'pe_freq', 0.2, ...
    'tol_cnt', 0, ...
    'TOL_TIME', 3, ...
    'tol_ts', 0, ...
    'tol_tf', 0, ...
    'LOCALIZATION_TOLERANCE', 5e-3);

A = [Leader, F1, F2];

% Set initial point
if(strcmp(F.formation_mode,"Random"))
    pos0 = r*(rand(dim_xy, n_agent) - 0.5);
    att0 = 2*pi*(rand(dim_th, n_agent) - 0.5);
else
    pos0 = [-0.8483    0.0616    1.5680; %x
   -0.8921    0.5583   -0.5402]; % y
    att0 = [0.4324   -0.1923   -3.0668];
end

for k=1:n_agent
    A(k).pos = pos0(:,k);
    A(k).att = att0(k);
end
