% simulation time
t = struct( ...
    'start', 0, ...
    'final', 500, ...
    'ts', 0.01, ...
    'time', 0, ...
    'length', 0);

t.time = t.start : t.ts : t.final-t.ts;
t.length = length(t.time);

% Utils
D2R = pi/180;
R2D = 1/D2R;